export { default as useCopy } from "./useCopy";
export { default as useDebounce } from "./useDebounce";
export { default as useEventListener } from "./useEventListener";
export { default as useLocalStorage } from "./useLocalStorage";
export { default as useMediaQuery } from "./useMediaQuery";
export { default as useOnClickOutside } from "./useOnClickOutside";
export { default as useOnKeyPress } from "./useOnKeyPress";
export { default as usePrefersDarkMode } from "./usePrefersDarkMode";
export { default as usePrefersReducedMotion } from "./usePrefersReducedMotion";
export { default as useSize } from "./useSize";
export { default as usePointerDevice } from "./usePointerDevice";
export { default as usePrintContent } from "./usePrintContent";
export { default as useSmartEffect } from "./useSmartEffect";
export { default as useThrottle } from "./useThrottle";
export { default as useToggle } from "./useToggle";
export { default as useWindowFocus } from "./useWindowFocus";
export { default as useWindowSize } from "./useWindowSize";

export { useIsTouchDevice } from "./usePointerDevice";
export { useIsDesktopDevice } from "./usePointerDevice";
